feat:Add beneficiaries connection #38
ISPP-07/frontend-acat pull request #40
Opened 2024-03-09 17:25 UTC by Manuelgruiz

# Description
Implemented a new feature that connects beneficiaries and interventions with backend.

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2024-03-09 17:49 UTC, Manuelgruiz commented
I've established the connection to beneficiaries, but I've changed an attribute to date and haven't been able to connect intervention because I don't have the GET request in the backend.

2024-03-09 19:23 UTC, JaviGarc1a requested changes
I can't run the backend, but you should add error handling in both fetches. In the catch you add the following text "No hay datos" and you wrap fetch with Suspense component with a fallback. Example fallback:
```html
<div>Cargando...</div>
```

You ask Álvaro about the vercel problem and try to fix it.

2024-03-14 10:21 UTC, sebasruii requested changes
![image](https://github.com/ISPP-07/frontend-acat/assets/73228845/afbf0c02-897e-427a-a1df-5abbc4254125)
Fetch interventions is still connected to MockAPI

2024-03-14 10:21 UTC, sebasruii commented on src/app/interventions/fetchIntervention.js
This fetcch still uses mockAPI, it should be connected to backend

2024-03-14 10:41 UTC, sebasruii approved these changes
Good job!

2024-03-14 10:42 UTC, sebasruii commented
Please, fix the conflicts and I will merge

2024-03-14 10:48 UTC, sebasruii approved these changes

2024-03-14 10:49 UTC, sebasruii commented
Since @JaviGarc1a  is not available this week, I'll be taking over and merge this PR

2024-03-14 10:49 UTC, merged